services:
  db:
    image: postgres:16
    container_name: restobook-db
    environment:
      POSTGRES_USER: restobook
      POSTGRES_PASSWORD: restobook123
      POSTGRES_DB: restobook
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:7
    container_name: restobook-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  pgadmin:
    image: dpage/pgadmin4
    container_name: restobook-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@restobook.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
  mongodata: