services:

  app:
    build: .
    container_name: restobook-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: restobook
      DB_PASSWORD: restobook123
      DB_NAME: restobook
      MONGO_URL: mongodb://mongo:27017/restobook
    depends_on:
      - db
      - mongo
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: restobook-db
    environment:
      POSTGRES_USER: restobook
      POSTGRES_PASSWORD: restobook123
      POSTGRES_DB: restobook
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: restobook-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: restobook-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@restobook.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
  mongodata: